Added SCSS/SASS support, fixed weird webpack file inclusion
Retmod/template-optimized pull request #1
Opened 2022-12-22 11:13 UTC by FishingHacks

2022-12-22 11:13 UTC, FishingHacks commented
why did you have the sass-loader and sass package installed?

2022-12-25 16:59 UTC, RedCrafter07 requested changes
Very good. Thanks for the PR! Although I wouldn't put the version thing in by default. Do you see any necessity in that? I don't see APIs which have a version endpoint often.

2022-12-25 16:59 UTC, RedCrafter07 commented on server/index.ts
> +app.get('/api/version', (req, res) => {
Well made, although I think the version thing is not really needed

2022-12-25 17:52 UTC, FishingHacks commented
While yes, there's not much use to that, i have implemented it to show off, how you can use the api. I believe that often-used features have to be given as an example in an pre-configured project. The /version endpoint was a way to show the user how to use routing, the query and .send(...)/.json(...)

2022-12-29 22:01 UTC, RedCrafter07 commented
Hmm, right

2022-12-29 22:01 UTC, RedCrafter07 approved these changes

2022-12-29 22:01 UTC, merged